name: Linting Python

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.type }}
  cancel-in-progress: true

on: [push]

jobs:

  Syntax-Check--Static-Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Get pip Cache Dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install flake8 pylint pytest
          # add project packages for pylint
          python -m pip install numpy matplotlib pandas GitPython batchedmoments
          python -m pip install torch==1.8.2+cpu torchvision==0.9.2+cpu -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
          python -m pip install miniflask>=2.0.0

      - name: Syntax Check
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Static Analysis
        run: |
          flake8 src --count --ignore E501,W503 --statistics
          pylint -d W0511 -d C0114 -d C0116 -d C0115 -d C0301 -d C0103 -d R0913 -d R0914 -d R0902 -d R0912 -d R0801 -d W0212 -d W0223 -d E1101 -d W0221 -d E1102 `find . -type f -name '.module' -printf '%h\0' | sort -zu | sed -z 's/$/\n/' | tr -d '\0'`

      - name: Static Analysis (Warnings)
        run: |
          pylint --exit-zero `find . -type f -name '.module' -printf '%h\0' | sort -zu | sed -z 's/$/\n/' | tr -d '\0'`
